name 'puppet-module-proxy'
version '0.2.0'
source 'git://github.com/emahags/puppet-module-proxy.git'
author 'emahags'
license 'Apache License, Version 2.0'
summary 'Manage proxy settings'
description 'Manage proxy settings'
project_page 'https://github.com/emahags/puppet-module-proxy'

dependency 'puppetlabs/stdlib', '>= 4.2.0'
